### PR TITLE
New Get-HRRest cmdlet that gives you the lowest heart rate of the day

### PR DESCRIPTION
**Pull request by jansenbe**
I'm using your excellent cmdlets to pull down all HR data in order to find my correct resting HR. Made a simple new cmdlet to make this easier...can be useful for other folks as well, hence the PR

### CODE REVIEW

**Comment by CollinChaffin** [comment]
I'm confused.  This pull requests shows a single cmd for get resting rate and I'll have to decide whether that's something I want since this graphs and pulls all data but your comment makes absolutely no sense.  This IS a full cmdlet that's entire purpose is to do one thing - pull down ALL heartrate data for 24 hr period and anther cmd to then pull it for an entire month (with a ton of logic around it).

EDIT:  I think I misread so please confirm that the only thing your PR is adding is the ability to parse out and compute the single value the lowest rate of the day?

**Comment by CollinChaffin** [comment]
Before I merge this, I already was working on something similar to do what I already have Excel doing - providing both the highest, lowest (resting), and average HR for each day on the chart, but at the cmdline to be able to then utiize that in the pipeline.  It looks like that's what you're going for, but only focusing on the one value the lowest (resting).  If true, I'd like to add the other 2 as well (highest and average) to make that cmd set complete before implementing.

So, if you want to take a stab at copying your code and adjusting it to do MAX and AVG both under different cmdlet functions, that would be awesome!  Otherwise, I may actually have a bit of time finally later today or tonight to do it and then we can roll in your change.

**Comment by jansenbe** [comment]
Hi Collin,

The change I did is indeed a very simple one as I wanted to avoid the overhead of pushing data to Excel for just knowing my lowest HR. I like you idea about also listing avg/max...Shall rename the cmdlets to Get-HRMin, GetHRAvg and GetHR-Max and add the missing ones.

**Comment by jansenbe** [comment]
Updated this PR with the three cmdlets: Get-HRMin, GetHRAvg and GetHR-Max. Note that these cmdlets also return the calculated value so that you can use these cmdlets in other scripts (e.g. to persist the data in a database).

**Pull request closed without merging**
